version: "3"
services:
  server:
    build: server
    command: dotnet run
    ports:
      - "5000:5000"
    volumes:
      - ./server/code:/code
  web:
    build: web
    command: npm start
    ports:
      - "3000:3000"
    volumes:
     - ./web/code:/code

