version: "3"
services:
  server:
    build: server
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
    volumes:
      - ./server/code:/code
  web:
    build: web
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./web/code:/code
  db:
    image: postgres:10.1-alpine
