version: "3"
services:
  server:
    build: server
    command: bin/console server:run
    ports:
      - "8000:8000"
    volumes:
      - ./server/code:/code
  web:
    build: web
    command: npm start
    ports:
      - "3000:3000"
    volumes:
     - ./web/code:/code
