version: "3"
services:
  server:
    build: server
    command: dotnet run --project Jirotal
    ports:
      - "5000:5000"
    volumes:
      - ./server:/code
  web:
    build: web
    command: npm start
    ports:
      - "3000:3000"
    volumes:
     - ./web:/code

